### ISSUE TITLE
change the apt-get upgrade process

### ISSUE THREAD

**Issue by irgendwr** [Sinusbot/installer-linux#71]
Current problems:
- the CI is broken because the package upgrade fails
- users complain about errors that are caused by their broken sources.list or other unrelated packages

We can't fix the random broken sources.list/packages that users have but to partially solve both issues I would recommend two changes:

1. Don't force the user to upgrade packages.
  It's fine to make upgrading the default and not provide support for outdated/broken systems but forcing the users to upgrade is a bad decision imo.
2. Don't quit the installer if apt throws warnings or errors **as long as the required packages are installed**.
  This might not be easy to handle correctly but would be very nice to have.

**Comment by mxschmitt** [comment]
I would simply adjust this condition, so that the user can decide himself, if the system needs to be upgraded or not. Currently we will exit and stop with the installer, if the user selects that the system should not be updated. Related coding: https://github.com/SinusBot/installer-linux/blob/b08693499b03c4645db89c5f064c05807043ff97/sinusbot_installer.sh#L577-L604
